# Generated by Django 5.2 on 2025-07-07 08:49

import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalmentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activation_date', models.DateField(blank=False, null=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activation_date'], name='finance_ins_activat_9b3e62_idx')],
            },
        ),
    ]
